FXAutomation/Models/ICORE_CASE_SUBMISSION_FORM_VIEW.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICORE_CASE_SUBMISSION_FORM_VIEW
    {
        public string Dept_Code { get; set; }
        public string Dept_Name { get; set; }
        public Nullable<bool> Dept_Status { get; set; }
        public Nullable<decimal> Categ_DeptId { get; set; }
        public Nullable<decimal> CaseType_CategoryId { get; set; }
        public string Categ_Code { get; set; }
        public string Categ_Name { get; set; }
        public string Categ_Description { get; set; }
        public Nullable<bool> Categ_Status { get; set; }
        public decimal CaseTitle_Id { get; set; }
        public string CaseTitle_Code { get; set; }
        public string CaseTitle_Name { get; set; }
        public string CaseTitle_Description { get; set; }
        public Nullable<bool> CaseTitle_Status { get; set; }
        public decimal Dept_Id { get; set; }
        public Nullable<decimal> CaseTitle_CaseTypeId { get; set; }
        public string CaseType_Code { get; set; }
        public string CaseType_Name { get; set; }
        public string CaseType_Description { get; set; }
        public Nullable<bool> CaseType_Status { get; set; }
        public decimal Categ_Id { get; set; }
        public decimal CaseType_Id { get; set; }
    }
}

FXAutomation/Controllers/Icore_CaseSubmission_FormController.cs
using FXAutomation.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace FXAutomation.Controllers
{
    public class Icore_CaseSubmission_FormController : Controller
    {
        FXDIGEntities context = new FXDIGEntities();
        // GET: Icore_CaseSubmission_Form
        [DllImport(@"urlmon.dll", CharSet = CharSet.Auto)]
        private extern static System.UInt32 FindMimeFromData(System.UInt32 pBC,
        [MarshalAs(UnmanagedType.LPStr)] System.String pwzUrl,
        [MarshalAs(UnmanagedType.LPArray)] byte[] pBuffer,
        System.UInt32 cbSize, [MarshalAs(UnmanagedType.LPStr)] System.String pwzMimeProposed,
        System.UInt32 dwMimeFlags,
        out System.UInt32 ppwzMimeOut,
        System.UInt32 dwReserverd);
        public FileContentResult ViewFile(int ID = 0)
        {
            if (Session["USER_ID"] != null)
            {
                string SessionUser = Session["USER_ID"].ToString();
                if (DAL.CheckFunctionValidity("Icore_SubmittedCase", "OpsQueue", Session["USER_ID"].ToString()) || DAL.CheckFunctionValidity("Icore_SubmittedCase", "ComplianceQueue", Session["USER_ID"].ToString()) || DAL.CheckFunctionValidity("Icore_SubmittedCase", "RegulatoryHead", Session["USER_ID"].ToString()))
                {
                    if (DAL.CheckFormQueue(ID.ToString(), SessionUser))
                    {
                        if (ID != 0)
                        {
                            ICORE_SUBMIT_CASE_DOCUMENT_VIEW GetFile = context.ICORE_SUBMIT_CASE_DOCUMENT_VIEW.Where(m => m.SCD_ID == ID).FirstOrDefault();
                            string FileAddress = GetFile.SCD_DOCUMENT_VALUE;
                            string FileToOpen = Path.GetFileName(FileAddress);
                            string filePath = FileAddress;  //HttpContext.Server.MapPath(@"~/Uploads/" + FileToOpen);
                            if (System.IO.File.Exists(filePath))
                            {
                                byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
                                string mimeType = "application/pdf";
                                string FileNameDisplay = GetFile.Case_Doc_Name + "." + GetFile.Format_extension;
                                Response.AppendHeader("Content-Disposition", "inline; filename=" + FileNameDisplay);
                                return File(fileBytes, mimeType);
                            }
                            else
                            {
                                string FilePath = "";
                                string localPath = "";
                                ICORE_CASE_DOCUMENTS GetDocDetail = context.ICORE_CASE_DOCUMENTS.Where(m => m.Case_Doc_Id == GetFile.SCD_DOCUMENT_ID).FirstOrDefault();
                                if (GetDocDetail != null)
                                {
                                    ICORE_SYSTEM_SETUP SystemData = context.ICORE_SYSTEM_SETUP.Where(m => m.SS_ID == 1).FirstOrDefault();
                                    if (SystemData != null)
                                    {
                                        string FileDomain = SystemData.SS_DOMAIN_FOR_WEB;
                                        if (GetDocDetail.Case_Doc_IsAD == true)
                                            FilePath = FileDomain + "IUploads/" + FileToOpen;
                                        else
                                            FilePath = FileDomain + "Uploads/" + FileToOpen;
                                        if (System.IO.File.Exists(FilePath))
                                        {
                                            localPath = new Uri(FilePath).LocalPath;
                                        }
                                        else
                                        {
                                            FileDomain = SystemData.SS_DOMAIN_FOR_CLIENT;
                                            if (GetDocDetail.Case_Doc_IsAD == true)
                                                FilePath = FileDomain + "IUploads/" + FileToOpen;
                                            else
                                                FilePath = FileDomain + "Uploads/" + FileToOpen;
                                            localPath = new Uri(FilePath).LocalPath;
                                        }
                                        // Check Here if System Have Permissions To View File on Network
                                    }
                                    else
                                    {
                                        string message = "";
                                        message = "No data found in the System Setup.";
                                        return CreateLogFile(message);
                                    }
                                    try
                                    {
                                        System.IO.File.OpenRead(localPath);
                                    }
                                    catch (Exception ex)
                                    {
                                        string message = "";
                                        message = "File : " + FileToOpen + " Exception : " + ex.Message;
                                        return CreateLogFile(message);
                                    }
                                    if (System.IO.File.Exists(localPath))
                                    {
                                        byte[] fileBytes = System.IO.File.ReadAllBytes(localPath);
                                        string mimeType = "application/pdf";
                                        string FileNameDisplay = GetFile.Case_Doc_Name + "." + GetFile.Format_extension;
                                        Response.AppendHeader("Content-Disposition", "inline; filename=" + FileNameDisplay);
                                        return File(fileBytes, mimeType);
                                    }
                                    else
                                    {
                                        string message = "";
                                        message = "File : " + FileToOpen + " not found in the given path." + Environment.NewLine + "please check permissions.";
                                        return CreateLogFile(message);
                                    }
                                }
                            }
                        }
                        else
                        {
                            string message = "";
                            message = "Error while fecting document at ID : " + ID;
                            return CreateLogFile(message);
                        }
                    }
                    else
                    {
                        string message = "";
                        message = "Unauthorized User, unable to process the request.";
                        return CreateLogFile(message);
                    }
                }
                else
                    return null;
            }
            return null;
        }
        public FileContentResult CreateLogFile(string Message)
        {
            var byteArray = System.Text.Encoding.ASCII.GetBytes(Message);
            var stream = new System.IO.MemoryStream(byteArray);
            var logfile = new FileContentResult(stream.ToArray(), "text/plain");
            return logfile;
        }
        public PartialViewResult ViewSubmittedCaseForm(decimal? SCFM_ID)
        {
            if (Session["USER_ID"] != null && Request.IsAjaxRequest())
            {
                if (DAL.CheckFunctionValidity("Icore_SubmittedCase", "OpsQueue", Session["USER_ID"].ToString()) || DAL.CheckFunctionValidity("Icore_SubmittedCase", "ComplianceQueue", Session["USER_ID"].ToString()) || DAL.CheckFunctionValidity("Icore_SubmittedCase", "RegulatoryHead", Session["USER_ID"].ToString()))
                {
                    if (DAL.CheckFormQueueForFieldsAndDocuments(SCFM_ID, Session["USER_ID"].ToString()))
                    {
                        List<ICORE_SUBMIT_CASE_FORM_FIELD_DETAIL_VIEW> data = new List<ICORE_SUBMIT_CASE_FORM_FIELD_DETAIL_VIEW>();
                        if (SCFM_ID != 0)
                        {
                            data = context.ICORE_SUBMIT_CASE_FORM_FIELD_DETAIL_VIEW.Where(m => m.SCFD_SCFM_ID == SCFM_ID).OrderBy(m => m.CaseForm_Data_ORDER_BY).ToList();
                        }
                        return PartialView(data);
                    }
                    else
                        return PartialView(null);
                }
                else
                {
                    return PartialView(null);
                }
            }
            else
            {
                return PartialView();
            }            
        }
        public PartialViewResult ViewSubmittedDocument(decimal? SCFM_ID)
        {
            if (Session["USER_ID"] != null && Request.IsAjaxRequest())
            {
                if (DAL.CheckFunctionValidity("Icore_SubmittedCase", "OpsQueue", Session["USER_ID"].ToString()) || DAL.CheckFunctionValidity("Icore_SubmittedCase", "ComplianceQueue", Session["USER_ID"].ToString()) || DAL.CheckFunctionValidity("Icore_SubmittedCase", "RegulatoryHead", Session["USER_ID"].ToString()))
                {
                    if (DAL.CheckFormQueueForFieldsAndDocuments(SCFM_ID,Session["USER_ID"].ToString()))
                    {
                        List<ICORE_SUBMIT_CASE_DOCUMENT_VIEW> ViewData = new List<ICORE_SUBMIT_CASE_DOCUMENT_VIEW>();
                        if (SCFM_ID != null)
                        {

FXAutomation/Views/Icore_CaseSubmission_Form/Submission_Form.cshtml
@model FXAutomation.Models.ICORE_CASE_SUBMISSION_FORM_VIEW
@{
    ViewBag.Title = "Case Submission Form";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Case Submission Forms";
}
@{
    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fa fa-times"></span></button>
            @ViewBag.message
        </div>

    }
}
@using (Html.BeginForm("Submission_Form", "Icore_CaseSubmission_Form", FormMethod.Post, new { id = "Submission_Form_Temp" }))
{
    <div id="CaseFormSubmissionView">
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.CaseType_CategoryId)
        @Html.HiddenFor(m => m.CaseTitle_CaseTypeId)

        <div class="card card-default card-outline">
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="case_form_case_type">Select Department</label>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.Dept_Id, null, new { @class = "form-control select2 select2-primary" })
                                    @Html.ValidationMessageFor(model => model.Dept_Id, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="case_form_case_type">Select Category</label>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.Categ_DeptId, null, new { @class = "form-control select2 select2-primary", @id = "Categ_DeptId" })
                                    @Html.ValidationMessageFor(model => model.Categ_DeptId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="case_form_case_type">Select Case Type</label>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.CaseType_Id, null, new { @class = "form-control select2 select2-primary" })
                                    @Html.ValidationMessageFor(model => model.CaseType_Id, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="case_form_case_type">Select Case Title</label>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.CaseTitle_Id, null, new { @class = "form-control select2 select2-primary" })
                                    @Html.ValidationMessageFor(model => model.CaseTitle_Id, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<!-- Case Form View on ajax call -->
<div class="card card-primary card-outline">
    <div class="card-header">
        <h3 class="card-title">Form Documents</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
        </div>
    </div>

    <p>

    </p>
    <!--#region Card-header -->
    <div class="card-body">
        <div id="CaseForm_PartialView">

        </div>
        <div id="CaseDocument_PartialView">

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="FormSubmission" value="Submit" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
</div>
<div id="CaseSubmittedFormList">

</div>
<div class="modal fade" id="modal-xl">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Submitted Form</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="SubmittedCaseFormFields"></div>

                <div id="SubmittedCaseDocument"></div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                <h4><b>FX</b> Digitalization</h4>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

FXAutomation/Views/Icore_CaseSubmission_Form/UpdateSubmittedFormAD.cshtml
@model FXAutomation.Models.EditSubmittedFormAD

@{
    ViewBag.Title = "Submitted Case";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Submitted Case";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fas fa-times"></span></button>
            @ViewBag.message
        </div>

    }
}
<a href="@Url.Action("OpsQueue","Icore_SubmittedCase")" class="btn btn-outline-primary">Back</a>
<hr />
@using (Html.BeginForm("UpdateSubmittedFormAD", "Icore_CaseSubmission_Form", FormMethod.Post))
{
    var FormID = Model.Master.SCFM_ID;
    <div id="EditSubmittedForm">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Master.SCFM_ID)

        <div class="card">
            <div class="card-header citi-table-head">
                <h3 class="card-title">Saved Form</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                </div>
            </div>
            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <!--#region Form Name-->
                @foreach (var item in Model.FieldList.Take(1))
                {
                    <h1 class="text-center">Form : <span class="text-uppercase city-default-font-color">@item.CaseForm_Name</span></h1>
                }
                <hr />
                <p class="list">Fileds with <span class="text-red require-font-size"><b>*</b></span> are required.</p>
                <hr />
                <!--#endregion-->
                <div class="row">
                    @{
                        int currentrow = 0;
                    }
                    @foreach (var item in Model.FieldList)
                    {
                        currentrow += 1;
                        string FieldId = "ctrlfrmsub" + item.CaseForm_Field_Name.Replace(" ", "").Substring(0, 3).ToString() + item.SCFD_FIELD_ID;
                        <div class="col-md-12">
                            <div class="row">
                                @if (item.CaseForm_Filed_IsAD == true)
                                {
                                    <div class="col-md-2">
                                        @{
                                            if (item.CaseForm_Field_IsRequired == true)
                                            {
                                                <label><span class="text-red require-font-size">*</span> @item.CaseForm_Field_Name</label>
                                            }
                                            else
                                            {
                                                <label>@item.CaseForm_Field_Name</label>
                                            }
                                        }
                                    </div>
                                    <div class="col-md-10">
                                        @Html.EditorFor(modelItem => item.SCFD_FIELD_VALUE, new { htmlAttributes = new { @class = "form-control", @id = FieldId, @maxlength = item.CaseForm_Data_MAX_LENGTH } })
                                    </div>
                                }
                                else
                                {
                                    <div class="col-md-2">
                                        @{
                                            if (item.CaseForm_Field_IsRequired == true)
                                            {
                                                <label><span class="text-red require-font-size">*</span> @item.CaseForm_Field_Name</label>
                                            }
                                            else
                                            {
                                                <label>@item.CaseForm_Field_Name</label>
                                            }
                                        }
                                    </div>
                                    <div class="col-md-10">
                                        @Html.EditorFor(modelItem => item.SCFD_FIELD_VALUE, new { htmlAttributes = new { @class = "form-control", @id = FieldId, @maxlength = item.CaseForm_Data_MAX_LENGTH, @readonly = "readonly" } })
                                    </div>
                                }
                            </div>
                            <hr />
                        </div>
                    }
                </div>
                <h1>Attached Documents</h1>
                <hr />
                <p class="list">Documents with <span class="text-red require-font-size"><b>*</b></span> are required.</p>
                <p class="list">Document Names should be of naming convention: <Document Name>.pdf e.g for Cover Letter, name should be "Cover Letter.pdf"</p>
                <p class="list">Document Names should not contain any special characters i.e & # + % \ / : * ? "</p>
                <p class="list">Only PDF extention is allowed. (For additional documents doc, docx, xls, xlsx, pdf, txt, csv, ppt, pptx extensions are allowed)</p>
                <p class="list">Documents size should not exceed 5MB.</p>
                <hr />
                <div class="row" id="SavedDocument">
                    @{
                        int no_of_row = 0;
                    }
                    @foreach (var item in Model.DocumentList)
                    {
                        no_of_row += 1;
                        string DocId = "ctrldocsub" + item.Case_Doc_Name.Replace(" ", "").Substring(0, 3).ToString() + item.SCD_DOCUMENT_ID;
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-2">
                                    @{
                                        if (item.Case_Doc_IsRequired == true)
                                        {
                                            <label><span class="text-red require-font-size">*</span> @item.Case_Doc_Name</label>
                                        }
                                        else
                                        {
                                            <label>@item.Case_Doc_Name</label>
                                        }
                                    }
                                </div>
                                <div class="col-md-7">
                                    @if (item.Case_Doc_IsAD == true)
                                    {
                                    <input type="file" class="form-control citi-table-head" id="@DocId" accept=".@item.Format_extension">
                                    }
                                    else
                                    {
                                    <input type="file" class="form-control citi-table-head" disabled id="@DocId" accept=".@item.Format_extension">
                                    }       
                                </div>
                                <div class="col-md-3">
                                    @{
                                        if (item.Case_Doc_IsAD == true)
                                        {
                                            if (item.SCD_DOCUMENT_VALUE != null && item.SCD_DOCUMENT_VALUE != "")
                                            {
                                                int ix = item.SCD_DOCUMENT_VALUE.IndexOf("Uploads");

                                                if (ix != -1)
                                                {
                                                    string WebDomain = Request.Url.GetLeftPart(UriPartial.Authority);
                                                    string FinalDomain = WebDomain + "/";
                                                    string DocumentURL = FinalDomain + item.SCD_DOCUMENT_VALUE.Substring(ix).Replace("\\", "/");
                                                    <a href="@Url.Action("ViewFile","Icore_CaseSubmission_Form", new { ID = item.SCD_ID})" target="_blank" class="btn btn-outline-primary" title="View @item.Case_Doc_Name file" data-toggle="tooltip">
                                                        View Previous File
                                                    </a>
                                                    @*<a href="@DocumentURL" target="_blank" class="btn btn-outline-primary"> View Previous File </a>*@
                                                }
                                                else
                                                {
                                                    <a href="#" class="btn btn-outline-primary"> View Previous File</a>
                                                }
                                            }
                                            else
                                            {
                                                <p class="btn btn-outline-warning"> No File Uploaded By AD </p>
                                            }
                                        }
                                        else
                                        {
                                            if (item.SCD_DOCUMENT_VALUE != null && item.SCD_DOCUMENT_VALUE != "")
                                            {
                                                int ix = item.SCD_DOCUMENT_VALUE.IndexOf("Uploads");

                                                if (ix != -1)
                                                {
                                                    <a href="@Url.Action("ViewFile","Icore_CaseSubmission_Form", new { ID = item.SCD_ID})" target="_blank" class="btn btn-outline-primary" title="View @item.Case_Doc_Name file" data-toggle="tooltip">
                                                        View Previous File
                                                    </a>
                                                    @*<a href="@DocumentURL" target="_blank" class="btn btn-outline-primary"> View Previous File </a>*@
                                                }
                                                else
                                                {
                                                    <p class="btn btn-outline-warning"> No File Uploaded By Client </p>
                                                }
                                            }
                                            else
                                            {
                                                <p class="btn btn-outline-warning"> No File Uploaded By Client </p>
                                            }
                                        }
                                    }
                                </div>
                            </div>
                            <hr />
                        </div>
                    }
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" value="@FormID" name="EditSubittedFormAD" class="btn btn-outline-primary">
                            Submit
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

FXAutomation/Views/Icore_CaseSubmission_Form/ViewSubmittedCaseForm.cshtml
@model IEnumerable<FXAutomation.Models.ICORE_SUBMIT_CASE_FORM_FIELD_DETAIL_VIEW>

@{
    ViewBag.FormName = "";
}
@foreach (var Items in Model.Take(1))
{
    <h1>Form : @Items.CaseForm_Name</h1>
    <hr />
}
    <div class="row">
        @foreach (var item in Model)
        {
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label><span>@item.CaseForm_Data_ORDER_BY ) </span> @item.CaseForm_Field_Name</label>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" value="@item.SCFD_FIELD_VALUE" class="form-control" readonly="readonly" />
                        </div>
                    </div>
                </div>
            </div>
            <hr class="hr-margin" />
        </div>
        }
    </div>