FXAutomation_Client_Portal/Controllers/SubmittedFormStatusController.cs
using FXAutomation_Client_Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FXAutomation_Client_Portal.Controllers
{
    [CustomRequestFilter]
    public class SubmittedFormStatusController : Controller
    {
        FXDIGEntities context = new FXDIGEntities();
        // GET: SubmittedFormStatus
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult SubmittedCaseForm()
        {
            if (Session["USER_ID"] != null)
            {
                //string UserEmail = Session["USER_ID"].ToString();
                string UserPartyId = Session["USER_PARTY_ID"].ToString();
                var PartialData = context.ICORE_SUBMIT_CASE_FORM_FIELD_MASTER_VIEW.Where(m => m.SCFM_PARTY_ID == UserPartyId).OrderByDescending(m => m.SCFM_ID).ToList();
                return View(PartialData);
            }
            else
            {
                return RedirectToAction("Logout", "fxdig");
            }
        }
        [OutputCache(Duration = 10, VaryByParam = "*")]
        public PartialViewResult ViewSubmittedCaseOnModal()
        {
            if (Session["USER_ID"] != null)
            {

                string UserEmail = Session["USER_ID"].ToString();
                string Party_ID = Session["USER_PARTY_ID"].ToString();
                ICORE_CLIENT_PORTFOLIO GetClientData = context.ICORE_CLIENT_PORTFOLIO.Where(m => m.CP_EMAIL == UserEmail && m.CP_PARTY_ID == Party_ID).FirstOrDefault();
                if (GetClientData != null)
                {
                    ViewBag.CP_CONTACT = GetClientData.CP_CONTACT == null ? "" : GetClientData.CP_CONTACT;
                    ViewBag.CP_NAME = GetClientData.CP_NAME == null ? "" : GetClientData.CP_NAME;
                }
                var PartialData = context.ICORE_SUBMIT_CASE_FORM_FIELD_MASTER_VIEW.Where(m => m.SCFM_INSERTED_BY == UserEmail).OrderByDescending(m => m.SCFM_ID).ToList();
                return PartialView(PartialData);
            }
            else
            {
                return PartialView();
            }
        }
        public PartialViewResult LoadPreviousMasterCaseComments(string CaseNo)
        {
            if (Session["USER_ID"] != null && Request.IsAjaxRequest())
            {
                List<ICORE_SUBMIT_CASE_COMMENTS> ViewData = context.ICORE_SUBMIT_CASE_COMMENTS.Where(m => m.SCC_CASE_NO == CaseNo).OrderByDescending(m => m.SCC_ID).ToList();
                return PartialView(ViewData);
            }
            else
            {
                return PartialView();
            }
        }
        [HttpPost]
        public ActionResult AddCommentToMasterLog(string CaseNo, string comment)
        {
            if (Session["USER_ID"] != null && Request.IsAjaxRequest())
            {
                string message = "";
                if (comment != null && comment != "" && comment.Length <= 999)
                {
                    ICORE_SUBMIT_CASE_COMMENTS log = new ICORE_SUBMIT_CASE_COMMENTS();
                    log.SCC_ID = Convert.ToInt32(context.ICORE_SUBMIT_CASE_COMMENTS.Max(m => (int?)m.SCC_ID)) + 1;
                    log.SCC_CASE_NO = CaseNo;
                    log.SCC_COMMENT = comment;
                    log.SCC_ADDED_BY = Session["USER_ID"].ToString();
                    log.SCC_ADDED_DATE_TIME = DateTime.Now;
                    log.SCC_IS_AD = false;
                    context.ICORE_SUBMIT_CASE_COMMENTS.Add(log);
                    int rowCount = context.SaveChanges();
                    if (rowCount > 0)
                    {
                        ICORE_SUBMIT_CASE_FORM_MASTER Master = new ICORE_SUBMIT_CASE_FORM_MASTER();
                        Master = context.ICORE_SUBMIT_CASE_FORM_MASTER.Where(m => m.SCFM_CASE_NO == CaseNo).FirstOrDefault();
                        if (Master != null)
                        {
                            Master.SCFM_COMMENT = comment;
                            context.Entry(Master).State = System.Data.Entity.EntityState.Modified;
                            rowCount = context.SaveChanges();
                            if (rowCount > 0)
                                return Json("Comment Added Successfully");
                            else
                                return Json("Problem while processing");
                        }
                        else
                            return Json("Unable to fetech form details against Case No: " + CaseNo);
                    }
                    else
                        return Json("Problem while processing");
                }
                else
                {
                    if (comment == "" || comment == null)
                        message = "Enter comment against the Case No:" + CaseNo;
                    else
                        message = "The maximum length for comment is 999";
                    return Json(message);
                }
            }
            else
                return Json("Invalid request");
        }
    }
}

FXAutomation_Client_Portal/Views/SubmittedFormStatus/LoadPreviousMasterCaseComments.cshtml
@model IEnumerable<FXAutomation_Client_Portal.Models.ICORE_SUBMIT_CASE_COMMENTS>

<!-- DIRECT CHAT -->
<div class="card direct-chat direct-chat-primary">
    <!-- /.card-header -->
    <div class="card-body">
        <!-- Conversations are loaded here -->
        <div class="direct-chat-messages">
            @{
                if (Model.Count() > 0)
                {
                    foreach (var item in Model)
                    {
                        <input type="hidden" id="GetCaseNoForComment" value="@item.SCC_CASE_NO" />

                        FXAutomation_Client_Portal.Models.FXDIGEntities cont = new FXAutomation_Client_Portal.Models.FXDIGEntities();
                        if (item.SCC_IS_AD == true)
                        {
                             <!-- Message. Default to the left -->
                            <div class="direct-chat-msg">
                                <div class="direct-chat-infos clearfix">
                                    @{
                                        string UserName = cont.ICORE_LOGIN.Where(m => m.LOG_USER_ID == item.SCC_ADDED_BY).Select(m => m.LOG_USER_NAME).FirstOrDefault();
                                    }
                                    <span class="direct-chat-name float-left">@UserName</span>
                                    <span class="direct-chat-timestamp float-right">@item.SCC_ADDED_DATE_TIME</span>
                                </div>
                                <div class="direct-chat-text">
                                    @item.SCC_COMMENT
                                </div>
                                <!-- /.direct-chat-text -->
                            </div>
                                        }
                                        else
                                        {
                            <!-- Message to the right -->
                                            <div class="direct-chat-msg right">
                                                <div class="direct-chat-infos clearfix">
                                                    @{
                                                        string UserName = cont.ICORE_CLIENT_PORTFOLIO.Where(m => m.CP_EMAIL == item.SCC_ADDED_BY).Select(m => m.CP_NAME).FirstOrDefault();
                                                    }
                                                    <span class="direct-chat-name float-right">@UserName</span>
                                                    <span class="direct-chat-timestamp float-left">@item.SCC_ADDED_DATE_TIME</span>
                                                </div>
                                                <div class="direct-chat-text">
                                                    @item.SCC_COMMENT
                                                </div>
                                                <!-- /.direct-chat-text -->
                                            </div>
                                                                }
                                                            }
                                                        }
                                                        else
                                                        {
                                                            <div class="text-center">
                                                                No Comments found against the document
                                                            </div>
                                                        }
            }
        </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        <form action="#" method="post">
            <div class="input-group">
                <input type="text" name="message" autocomplete="off" id="CommentsDataForMasterCase" placeholder="Type Message ..." class="form-control">
                <span class="input-group-append">
                    <button type="button" id="MasterCaseCommentFromSendButton" name="MasterCaseCommentFromSendButton" class="btn btn-primary">Send</button>
                </span>
            </div>
        </form>
    </div>
    <!-- /.card-footer-->
</div>
<!--/.direct-chat -->

FXAutomation_Client_Portal/Views/SubmittedFormStatus/SubmittedCaseForm.cshtml
@model IEnumerable<FXAutomation_Client_Portal.Models.ICORE_SUBMIT_CASE_FORM_FIELD_MASTER_VIEW>
@{
    ViewBag.Title = "Case Submission Form";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Case Submission Forms";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

            <div class="card card-primary">
                <div class="card-header" id="citi-card-header">
                    <h3 class="card-title">Submitted Form</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered text-center table-hover">
                        <thead class="citi-table-header">
                            <tr>
                                <th>
                                    Action
                                </th>
                                <th>
                                    Form Name
                                </th>
                                <th>
                                    Case Number
                                </th>
                                <th>
                                    Case Status
                                </th>
                                <th>
                                    Case Status Date
                                </th>
                                <th>
                                    Comment against the Case
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <button type="button" value="sp_@item.SCFM_ID _@item.SCFM_CASE_FORM_ID" class="btn btn-outline-primary" name="ViewSubmitted_Form" data-toggle="modal" data-target="#modal-xl" title="View @item.CaseForm_Name">
                                            <span class="fas fa-eye"></span>
                                        </button>
                                        @{
                                            if (item.SCFS_NAME.Contains("Discrepant"))
                                            {
                                                <a href="@Url.Action("EditSubmittedForm", "CaseSubmission_Form", new { Form_Id = item.SCFM_ID })" class="btn btn-outline-success" data-toggle="tooltip" title="Edit @item.CaseForm_Name">
                                                    <span class="fas fa-pen"></span>
                                                </a>
                                            }
                                        }
                                        @*<input type="button" value="View" class="btn btn-outline-primary" onclick="ViewSubmittedFormClick()" />*@
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CaseForm_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SCFM_CASE_NO)
                                    </td>
                                    <td id="badge-font-size">
                                            <span class="badge badge-warning" data-toggle="tooltip" title="@item.SCFS_DESCRIPTION">@Html.DisplayFor(modelItem => item.SCFS_NAME)</span>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SCFM_STATUS_DATE)
                                    </td>
                                    <td>
                                        @{
                                            if (item.SCFM_QUEUE == "Ops Queue")
                                            {
                                                if (item.SCFM_COMMENT != null)
                                                {
                                                    <button class="btn btn-outline-success btn-sm" title="Click here to reply" type="button" id="ViewPreviousCommentsOfMaster" name="ViewPreviousCommentsOfMaster" data-toggle="modal" data-target="#modal-lg" value="@item.SCFM_CASE_NO">
                                                        <span class="fas fa-reply"></span>
                                                    </button> 
                                                }
                                                @Html.DisplayFor(modelItem => item.SCFM_COMMENT)
                                            }
                                            else
                                            {
                                                <p></p>
                                            }
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="modal fade" id="modal-xl">
                <div class="modal-dialog modal-xl">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Submitted Form</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div id="SubmittedCaseFormFields"></div>
                            
                            <div id="SubmittedCaseDocument"></div>
                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                            <h4><b>FX</b> Digitalization</h4>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>

            <div class="modal fade" id="modal-lg">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Comment against the Case</h4>
                            <button type="button" id="CloseClientChatAgaintCase" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div id="LoadPreviousMasterCaseComments"></div>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>

FXAutomation_Client_Portal/Views/SubmittedFormStatus/SubmittedDocumentView.cshtml
@model IEnumerable<FXAutomation_Client_Portal.Models.ICORE_SUBMIT_CASE_DOCUMENT_VIEW>

@{

    string CurrentDomain = HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority);
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-8">
                    <label class="form-control">@item.Case_Doc_Name</label>
                </div>
                @{
                    int ix = item.SCD_DOCUMENT_VALUE.IndexOf("Uploads");

                    if (ix != -1)
                    {
                        string DocumentURL = CurrentDomain + item.SCD_DOCUMENT_VALUE.Substring(ix).Replace("\\", "/");
                        <a href="@DocumentURL" target="_blank" class="btn btn-outline-success"> View File </a>
                    }
                    else
                    {
                        <a href="#" class="btn btn-outline-success"> View File 2 </a>
                    }
                }
            </div>
        </div>
    }
</div>

FXAutomation_Client_Portal/Views/SubmittedFormStatus/ViewSubmittedCaseOnModal.cshtml
@model IEnumerable<FXAutomation_Client_Portal.Models.ICORE_SUBMIT_CASE_FORM_FIELD_MASTER_VIEW>


<div class="card citi-table-header collapsed-card">
    <div class="card-header border-0">
        <h3 class="card-title">
            <i class="fas fa-file-o mr-1"></i>
            Recently Submitted
        </h3>
        <!-- card tools -->
        <div class="card-tools">
            <button type="button" class="btn btn-default btn-sm" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
        </div>
        <!-- /.card-tools -->
    </div>
    <div class="card-body">
        @{
            if (Model != null)
            {
                if (Model.Count() > 0)
                {
                    foreach (var item in Model.Take(2))
                    {
                        <div class="row">
                            <div class="col-md-3" id="custom-label-font-size">Name : </div>
                            <div class="col-md-9" id="custom-font-size">@ViewBag.CP_NAME</div>
                        </div>
                        <div class="row" id="custom-font-size">
                            <div class="col-md-3" id="custom-label-font-size">Phone No : </div>
                            <div class="col-md-9" id="custom-font-size">@ViewBag.CP_CONTACT</div>
                        </div>
                        <div class="row" id="custom-font-size">
                            <div class="col-md-3" id="custom-label-font-size">Form : </div>
                            <div class="col-md-9" id="custom-font-size">@Html.DisplayFor(modelItem => item.CaseForm_Name)</div>
                        </div>
                        <div class="row" id="custom-font-size">
                            <div class="col-md-3" id="custom-label-font-size">Case No : </div>
                            <div class="col-md-9" id="custom-font-size">@Html.DisplayFor(modelItem => item.SCFM_CASE_NO)</div>
                        </div>
                        <div class="row" id="badge-font-size">
                            <div class="col-md-3" id="custom-label-font-size">Status : </div>
                            <div class="col-md-9" id="badge-font-size"><span class="badge badge-warning" data-toggle="tooltip" title="@Html.DisplayFor(modelItem => item.SCFS_DESCRIPTION)">@Html.DisplayFor(modelItem => item.SCFS_NAME)</span></div>
                        </div>
                        <hr />
                    }
                }
                else
                {
                   <p id="badge-font-size">No Case Form Submitted against Client : @Session["USER_NAME"].</p>
                }
            }

        }
    </div>
    <!-- /.card-body-->
    <div class="card-footer bg-transparent">
        <a href="@Url.Action("SubmittedCaseForm","SubmittedFormStatus")" class="btn btn-default">View Detail</a>
    </div>
</div>